'use client';

import { createFormHook } from '@tanstack/react-form';
import { fieldContext, formContext } from '@/hooks/form-context';
import {
	TextField,
	TextAreaField,
	SwitchField,
	BooleanField,
	SubmitErrors,
	PasswordField,
	SubscriptionTierField,
	ImagePickerField,
	ChannelSelectField,
	MultiSelectField,
	ChannelMultiSelectField,
	CategoryMultiSelectField,
	DateTimeField,
	TierListField,
	TicketClassesField,
	EventVenuesField,
	MoneyCentsField,
	ColorField,
	RichTextField,
	YoutubeLinkField,
	RumbleLinkField,
	HiddenField,
	NumberField,
	MFAField,
	PageSizeField,
	CategorySelectField,
	RoleSelectField,
	ContentTypeSelectField,
} from '@/components/forms/fields';
import {
	CreateButton,
	ResetButton,
	SaveChangesBar,
} from '@/components/forms/app-buttons';

export const { useAppForm, withForm, withFieldGroup } = createFormHook({
	fieldContext,
	formContext,
	fieldComponents: {
		TextField,
		TextAreaField,
		SwitchField,
		BooleanField,
		PasswordField,
		SubscriptionTierField,
		ImagePickerField,
		ChannelSelectField,
		MultiSelectField,
		ChannelMultiSelectField,
		CategoryMultiSelectField,
		DateTimeField,
		TierListField,
		TicketClassesField,
		EventVenuesField,
		MoneyCentsField,
		ColorField,
		RichTextField,
		YoutubeLinkField,
		RumbleLinkField,
		HiddenField,
		NumberField,
		MFAField,
		PageSizeField,
		CategorySelectField,
		RoleSelectField,
		ContentTypeSelectField,
	},
	formComponents: {
		SubmitErrors,
		CreateButton,
		ResetButton,
		SaveChangesBar,
	},
});
